### ISSUE TITLE
Feature request: map and unordered_map support?

### ISSUE THREAD

**Issue by laoshaw** [glouw/ctl#23]
even multiset and multimap, then a complete c++ stl replacement to some extent. :)

**Comment by glouw** [comment]
Fortunately set and unordered_set is close enough to map to not warrant full implementations in CTL. As for multi sets, this technically can be accomplished by combining a set with a list, but I haven't looked too far into it. Apart from the occasional bugfix, I do consider CTL done - I do not plan to add more features in the near future

**Comment by laoshaw** [comment]
cool Thanks!

**Comment by laoshaw** [comment]
just found out a forked repo has maps implemented though: https://github.com/rurban/ctl

**Comment by glouw** [comment]
Yeah, rurban is doing a pretty good job of pushing CTL to the extreme. I believe he works on perl11 so his work is pretty important to keep an eye on
